name: RimStart Native Image builds

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create-release
        uses: softprops/action-gh-release@v1
  build:
    name: Build native RimStart
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs: [create-release]
    steps:
      - uses: actions/checkout@v3

      - name: Add msbuild to PATH
        if: ${{ matrix.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Visual Studio shell
        if: ${{ matrix.os == 'windows-latest' }}
        uses: egor-tensin/vs-shell@v2

      - name: Install Linux libraries
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update
          sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev

      - uses: gluonhq/setup-graalvm@6eecc74f9ad1f028b863d7a494e351668a1b0370
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          jdk: 'java17'
          arch: 'x86_64'

      - name: Build RimStart
        run: |
          mvn -B gluonfx:build
      
      - name: Add Windows assets to release
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: target/gluonfx/x86_64-windows/RimStart.exe
          asset_name: RimStart.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Add Linux assets to release
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: target/gluonfx/x86_64-linux/RimStart
          asset_name: RimStart
          asset_content_type: application/x-executable
