name: RimStart Native Image builds

on:
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v1
  build:
    name: Build native RimStart
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'

      - name: Build RimStart
        run: |
          mvn -B gluonfx:build
      
      - name: Add Windows assets to release
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: target/gluonfx/x86_64-windows/RimStart.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Add Linux assets to release
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: target/gluonfx/x86_64-linux/RimStart
          asset_content_type: application/x-executable
